### ISSUE TITLE
Media upload fails

### ISSUE THREAD

**Issue by information-security** [getcandy/candy-api#78]
1) Uploading an image to media section of a product fails with 500 Internal Server Error for the request and malformed error message in UI.
2) Uploading large files fails with no appropriate error message in UI and 422 Unprocessable Entity for request.

## Expected Behavior
a) Image file must be uploaded and appears as an item in media section.
b) When uploading large files an error must indicate why file upload has failed

## Current Behavior
a)
![image](https://user-images.githubusercontent.com/4983612/47261498-76281780-d4dd-11e8-845d-97f8398e65fc.png)

![image](https://user-images.githubusercontent.com/4983612/47261518-c0a99400-d4dd-11e8-8776-24a65ed93250.png)

b)
![image](https://user-images.githubusercontent.com/4983612/47261376-b76af800-d4da-11e8-8880-799c55cb57ce.png)

![image](https://user-images.githubusercontent.com/4983612/47261611-a83a7900-d4df-11e8-99da-8b181e18dd26.png)

## Possible Solution
Not sure

## Steps to Reproduce
1. Follow instructions to install candy-store
2. Log into hub
3. Create a project
4. Edit the project and go to Media tab
5. a) Try to upload a jpg image from disk
5. b) Try to upload a large jpg (6.2MB) file from disk

## Context (Environment)
Since master branch is full of bugs and it is almost unusable, I used dev branches of api and hub in candy-store repo. I also had to do a few namespace modifications (mentioned here: https://github.com/getcandy/candy-api/issues/75#issuecomment-431155387) to get it working.

## Detailed Description
I suggest to merge dev into master branch more regularly to cover some serious bugs. master branch is 8 months outdated!!

## Possible Implementation

**Comment by information-security** [comment]
Problem (a) was due to a namespace problem caused by using dev branch. I made following changes in config/assets.php
```
        'vimeo' => GetCandy\Api\Assets\Drivers\Vimeo::class,
        'application' => GetCandy\Api\Assets\Drivers\File::class,
        'youtube' => GetCandy\Api\Assets\Drivers\YouTube::class,
        'image' => GetCandy\Api\Assets\Drivers\Image::class,
        'external' => GetCandy\Api\Assets\Drivers\ExternalImage::class
```
to
```
        'vimeo' => GetCandy\Api\Core\Assets\Drivers\Vimeo::class,
        'application' => GetCandy\Api\Core\Assets\Drivers\File::class,
        'youtube' => GetCandy\Api\Core\Assets\Drivers\YouTube::class,
        'image' => GetCandy\Api\Core\Assets\Drivers\Image::class,
        'external' => GetCandy\Api\Core\Assets\Drivers\ExternalImage::class
```

Now image is successfully uploaded and appears in media list but it has a problem with thumbnail generation. request to get thumbnail fails with 500 Internal Server Error and required directory path is not created (/storage/products/XW/thumbnails/thumbnail_XWZa0q0rkTVErEBDRxclv7NRRGZ1fuWVyvJn7mtI.png) I tried to create the path manually but nothing changed. In larval.log I see following messages:

```
[2018-10-20 23:54:39] local.ERROR: Undefined variable: language (View: /Users/farzan/candy-store-dev/resources/views/_includes/head.blade.php) (View: /Users/farzan/candy-store-dev/resources/views/_includes/head.blade.php) (View: /Users/farzan/candy-store-dev/resources/views/_includes/head.blade.php) {"exception":"[object] (ErrorException(code: 0): Undefined variable: language (View: /Users/farzan/candy-store-dev/resources/views/_includes/head.blade.php) (View: /Users/farzan/candy-store-dev/resources/views/_includes/head.blade.php) (View: /Users/farzan/candy-store-dev/resources/views/_includes/head.blade.php) at /Users/farzan/candy-store-dev/storage/framework/views/56836fb81f926e60191e7e8f43a4c5f2f9d63c9f.php:6, ErrorException(code: 0): Undefined variable: language (View: /Users/farzan/candy-store-dev/resources/views/_includes/head.blade.php) (View: /Users/farzan/candy-store-dev/resources/views/_includes/head.blade.php) at /Users/farzan/candy-store-dev/storage/framework/views/56836fb81f926e60191e7e8f43a4c5f2f9d63c9f.php:6, ErrorException(code: 0): Undefined variable: language (View: /Users/farzan/candy-store-dev/resources/views/_includes/head.blade.php) at /Users/farzan/candy-store-dev/storage/framework/views/56836fb81f926e60191e7e8f43a4c5f2f9d63c9f.php:6, ErrorException(code: 0): Undefined variable: language at /Users/farzan/candy-store-dev/storage/framework/views/56836fb81f926e60191e7e8f43a4c5f2f9d63c9f.php:6)
[stacktrace]
#0 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(45): Illuminate\\View\\Engines\\CompilerEngine->handleViewException(Object(ErrorException), 1)
#1 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/Users/farzan/b...', Array)
#2 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/View/View.php(142): Illuminate\\View\\Engines\\CompilerEngine->get('/Users/farzan/b...', Array)
#3 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/View/View.php(125): Illuminate\\View\\View->getContents()
#4 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/View/View.php(90): Illuminate\\View\\View->renderContents()
#5 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Illuminate\\View\\View->render()
#6 /Users/farzan/candy-store-dev/vendor/symfony/http-foundation/Response.php(202): Illuminate\\Http\\Response->setContent(Object(Illuminate\\View\\View))
#7 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(55): Symfony\\Component\\HttpFoundation\\Response->__construct(Object(Illuminate\\View\\View), 404, Array)
#8 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Routing/ResponseFactory.php(69): Illuminate\\Routing\\ResponseFactory->make(Object(Illuminate\\View\\View), 404, Array)
#9 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(379): Illuminate\\Routing\\ResponseFactory->view('errors::404', Array, 404, Array)
#10 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(288): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException(Object(Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException))
#11 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(187): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException))
#12 /Users/farzan/candy-store-dev/app/Exceptions/Handler.php(47): Illuminate\\Foundation\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException))
#13 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(83): App\\Exceptions\\Handler->render(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException))
#14 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(32): Illuminate\\Routing\\Pipeline->handleException(Object(Illuminate\\Http\\Request), Object(Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException))
#15 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#16 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#17 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#18 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /Users/farzan/candy-store-dev/vendor/itsgoingd/clockwork/Clockwork/Support/Laravel/ClockworkMiddleware.php(28): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Clockwork\\Support\\Laravel\\ClockworkMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /Users/farzan/candy-store-dev/vendor/barryvdh/laravel-cors/src/HandlePreflight.php(29): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(151): Barryvdh\\Cors\\HandlePreflight->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#35 /Users/farzan/candy-store-dev/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#36 /Users/farzan/candy-store-dev/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#37 {main}
"} 
```

Also, trying to download image fails with the same above message

**Comment by information-security** [comment]
Running `php artisan storage:link` fixed the problem with thumbnail and image loading. shouldn't this command be executed during installation or did I miss something in wiki instructions?

Problem with uploading large image files still persists.

**Comment by alecritson** [comment]
Have you tried to increase `ASSETS_MAX_FILESIZE` in the .env file? I have managed to upload large images locally.

We will be starting a release cycle when we hit beta, we appreciate it's a bit outdated on master at the moment.

**Comment by alecritson** [comment]
Have you tried to increase `ASSETS_MAX_FILESIZE` in the .env file? I have managed to upload large images locally.

We will be starting a release cycle when we hit beta, we appreciate it's a bit outdated on master at the moment.

**Comment by information-security** [comment]
@alecritson Thanks for your reply, I'm at least confident now that this project is continuing. Your work is really appreciable and I think it deserves more community attention than what it received so far.
I put ASSETS_MAX_FILESIZE=1000000 to .env file and tried uploading a 3.6MB jpg file but it made no difference and I am still getting same error.

Considering the fact that no documentations is available, having a working candy-store repo could help us learn more about API and HUB and therefore to put more contribution to your project from open-source community. Currently I am putting a lot of effort to just overcome a lot of difficulties I am facing to have a working candy-store installation. There are lots of errors (I can't even do a successful login to candy-store installation and a lot of hub's features are broken) and I am not sure if I need to post new issues for these problems or should I fix them locally.

**Comment by alecritson** [comment]
I'm not sure what could be causing the issue at this point, can you confirm what the PHP setting is for upload size?

Thanks for the feedback, if you find issues, feel free to post them on Github. Currently, it's in alpha so support for issues may be limited or it might be they are fixed for the next release. We are going to get a release schedule going as soon as possible.

**Comment by information-security** [comment]
How did I miss that obvious PHP setting!! Sorry for taking your time.
A combination of modifying `upload_max_filesize` in php.ini and adding `ASSETS_MAX_FILESIZE` to .env file solved this problem. You may now close this issue.

Thanks for your valuable notes though.

**Comment by alecritson** [comment]
Glad it solved the issue for you! and thanks again for the feedback.
